version: 2
jobs:
  build_deploy:
    docker:
      - image: node:12.13.0
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            npm run deploy:github
workflows:
  version: 2
  deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
