version: 2
jobs:
  build_deploy:
    docker:
      - image: node:12.13.0
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #       - '8e:e9:7b:ad:87:6d:67:da:ee:45:21:ab:d7:26:66:9e'
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run generate:gh-pages
      - run:
          name: Deploy
          command: npm run send:gh-pages
workflows:
  version: 2
  deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
